---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r}
#I load the first csv file from github
linkcsv="https://github.com/Fundamentals-Sarah/HW4/raw/refs/heads/main/maternal_cleaned.csv"
```
```{r}
#I import rio package for this file.
matmort=rio::import(file = linkcsv)
```


```{r}
#I load the second csv file from github
linkcsv2="https://github.com/Fundamentals-Sarah/HW4/raw/refs/heads/main/infantmortality_cleaned.csv"
```
```{r}
#I import rio package for this file.
infmort=rio::import(file = linkcsv2)
```

```{r}
#I load the third csv file from github
linkcsv3="https://github.com/Fundamentals-Sarah/HW4/raw/refs/heads/main/lifeexpectancy_cleaned.csv"
```
```{r}
#I import rio package for this file.
lifexclean=rio::import(file = linkcsv3)
```
```{r}
#Since I will be merging by Country Name, and each sheet has its own region column, I want to make the order of the columns Country Name, Region, then the remaining variable data elements. To do this, I reorder column names in my first spreadsheet so that Region column is second.
matmort <- matmort[ , c("Country_Name", "Region", "Maternal_Death_Rate")]
```

```{r}
#I take a look at what merging the maternal and infant mortality spreadsheets will look like
merge(matmort,infmort, by.x='Country_Name', by.y='Country_Name3')
```

```{r}
#I create the new data object merging maternal and infant mortality rates information
merge1 <- merge(matmort, infmort, by.x = "Country_Name", by.y = "Country_Name3")
```
```{r}
#I then see what merging maternal/infant mortality with life expectancy will look like
merge(merge1,lifexclean, by.x='Country_Name', by.y='Country_Name2')
```
```{r}
#I go ahead and merge the life expectancy data with the other two datasets
mergeall <- merge(merge1, lifexclean, by.x = "Country_Name", by.y = "Country_Name2")
```

```{r}
#I want to see all the column names that are now included in my merged data
names(mergeall)
```
```{r}
#I remove the repeating Region columns, since I just need one
merge_allclean <- mergeall[ , -c(5, 7)]
```

```{r}
#I check the overall view for the data frame I've generated
str(merge_allclean)
```

```{r}
#I make region a factor so it is considered categorical
merge_allclean$Region <- factor(merge_allclean$Region)
```


```{r}
#I check that region is now considered a factor
str(merge_allclean)
```

```{r}
#I save as an RDS file
saveRDS(merge_allclean,"merged_data.RDS")
```

```{r}
#I name my file and ensure it is pulled in correctly in the RDS format
mergeddataRDS=readRDS("merged_data.RDS")
str(mergeddataRDS)
```

```{r}
#I save my cleaned file as a csv
write.csv(merge_allclean,"merged_data_cleaned.csv", row.names=FALSE)
merged_data_cleanedCSV=read.csv("merged_data_cleaned.csv")
```

```{r}
#I check that the cleaned csv can be read in correctly
str(merged_data_cleanedCSV)
```
```{r}
#I install dplyr library
library(dplyr)
```
```{r}
#I explore what the data will look like if I aggregate by Region and calculate the median of the data element variables across each region
merge_allclean |>
  group_by(Region) |>
  summarize(Maternal_Death_Rate_Median = median(Maternal_Death_Rate),
            Infant_Mortality_Rate_Median = median(Infant_Mortality_Rate),
            Life_Expectancy_Median = median(Life_Expectancy))
```

```{r}
#I implement the operation above, naming the new data frame region_aggregate
region_aggregate <- merge_allclean |>
  group_by(Region) |>
  summarize(Maternal_Death_Rate_Median = median(Maternal_Death_Rate),
            Infant_Mortality_Rate_Median = median(Infant_Mortality_Rate),
            Life_Expectancy_Median = median(Life_Expectancy))
```

```{r}
#I save as an RDS file
saveRDS(region_aggregate,"regionaggregate.RDS")
```

```{r}
#I name my file and ensure it is pulled in correctly in the RDS format
regionaggregateRDS=readRDS("regionaggregate.RDS")
str(regionaggregateRDS)
```

```{r}
#I save my cleaned file as a csv
write.csv(region_aggregate,"regionaggregate.csv", row.names=FALSE)
regionaggregateCSV=read.csv("regionaggregate.csv")
```

```{r}
#I check that the cleaned csv can be read in correctly
str(regionaggregateCSV)
```

```{r}
#Taking the spreadsheet generated in Exercise 1, I remove the region column and name this data frame wide_format
wide_format <- merge_allclean[ , -c(2)]
```

```{r}
#I apply the long formatting to the wide_format version of the spreadsheet and generate it to check that it looks as expected
long_format=tidyr::pivot_longer(data=wide_format,
                                cols=!Country_Name, 
                                names_to = "CIA_Variable",
                                values_to = "Value")
long_format
```

```{r}
#I save as an RDS file
saveRDS(long_format,"long_format.RDS")
```

```{r}
#I name my file and ensure it is pulled in correctly in the RDS format
longformatRDS=readRDS("long_format.RDS")
str(longformatRDS)
```

```{r}
#I save my cleaned file as a csv
write.csv(long_format,"longformat.csv", row.names=FALSE)
longformatCSV=read.csv("longformat.csv")
```

```{r}
#I check that the cleaned csv can be read in correctly
str(longformatCSV)
```